access_token: ZDYyZGE3NWQtMWZiMi00ZjhkLTk1OTktYzk5YmQxMDAyNjI4NDhhOTllNTEtMDMz_PF84_18a7bab3-8072-414f-ad6a-d2c44826aef8
access_token_refresh: NTVhYzhhYjUtMTA0MS00YzNkLWJhZmYtOTY3ZjBjNzQzNDI1ZTk1YTI3OGYtMDI4_PF84_18a7bab3-8072-414f-ad6a-d2c44826aef8
archive_log: /opt/mastersystem-syslog/logs/sent_syslog.log
counter_msg_id: 1
filtered_log: /opt/mastersystem-syslog/logs/filtered_syslog.log
group_path: /opt/mastersystem-syslog/groups/
